baseURL = "http://example.org/"
languageCode = "en-us"
title = "Xiang Li"
theme = "PaperMod"  # your theme name

[menu]

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

  [[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 2

  [[menu.main]]
  name = "Talks"
  url = "/talks/"
  weight = 3
  
  [[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 4
  
  [[menu.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 5
  
  [[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 6